### ISSUE TITLE
New Release of microsoft.ad

### ISSUE THREAD

**Issue by LaurinStreng** [ansible-collections/microsoft.ad#103]
##### SUMMARY
I'm currently in the process of switching from the deprecated community.windows to the new microsoft.ad Modules in Ansible.
Therefore, the issue with long group names is blocking me. 
So my Question is, is it possible to release a new Version from microsoft.ad to include this Fix:
https://github.com/ansible-collections/microsoft.ad/pull/95

I would support with preparing the new Release if it is necessary.

##### ISSUE TYPE
New Release

##### COMPONENT NAME
win_domain_group_membership_module.html
microsoft.ad.group

##### ADDITIONAL INFORMATION
---

**Comment by jborean93** [comment]
Thanks for the prompt, I have just released [v1.5.0](https://github.com/ansible-collections/microsoft.ad/releases/tag/1.5.0) which should be live on Galaxy and will be approved in AH at some point soon.
