### ISSUE TITLE
MANIFEST.json required for installation

### ISSUE THREAD

**Issue by Adepablo** [ansible-collections/microsoft.ad#151]
##### SUMMARY
When installing the colletion, keep getting the following message:

ERROR! Collection at 'microsoft.ad-1.6.0.tar.gz' does not contain the required file MANIFEST.json.

Am I missing something? Is there anyway arround?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
Missing MANIFEST.json.

##### ANSIBLE VERSION
ansible [core 2.15.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.7 (main, Jan 26 2024, 15:26:41) [GCC 8.5.0 20210514 (Red Hat 8.5.0-21)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True

**Comment by jborean93** [comment]
Closing as per the above, the `MANIFEST.json` is built when publishing the collection.
