### ISSUE TITLE
Doc site unmaintained ?

### ISSUE THREAD

**Issue by markatdxb** [ansible-collections/microsoft.ad#161]
##### SUMMARY
I was just following the galaxy doc site link https://docs.ansible.com/ansible/devel/collections/microsoft/ad/
and seems its not maintained ? In docs are mentioned modules like "computer" which actually in the latest collection version dont exists 

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by jborean93** [comment]
The docsite is updated automatically based on what version of the collection the PyPI Ansible packages. There is definitely a [computer](https://github.com/ansible-collections/microsoft.ad/blob/main/plugins/modules/computer.ps1) module and the docs should be up to date.

**Comment by markatdxb** [comment]
You are right, there was a mistake in my playbook. What confused me though was the list of modules on Galaxy. Selecting version 1.6.0 I could see computer module but it's missing when selecting the 1.7.0 and later version. 
Anyway thank you for confirmation
