### ISSUE TITLE
How to secure credentials with microsoft.ad.ldap inventory plugin

### ISSUE THREAD

**Issue by pharriso** [ansible-collections/microsoft.ad#34]
##### SUMMARY
I can't see a way to secure the credentials required for microsoft.ad.ldap inventory plugin. The documented examples show the different authentication options, but how do you use the plugin without entering the credentials in plaintext? 

This will lead to issues using the plugin with AWX or automation controller where we would typically pull the inventory configuration from source control. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
microsoft.ad.ldap inventory plugin

##### ADDITIONAL INFORMATION

Typically inventory plugins have the option of using environment variables which allow us to source them from a project in AWX and then use custom credential types in AWX to inject the necessary environment variables. This means we don't need to store the credentials with the inventory configuration in source control.

Looking at nearly all inventory plugins you'll see examples of this. For example the AWX inventory plugin - https://docs.ansible.com/ansible/latest/collections/awx/awx/controller_inventory.html#ansible-collections-awx-awx-controller-inventory

**Comment by jborean93** [comment]
The PR https://github.com/ansible-collections/microsoft.ad/pull/37 adds environment variables starting with `MICROSOFT_AD_LDAP_` to the various connection and authentication options exposed by the inventory plugin.
