### ISSUE TITLE
Feature Request: Collection-level Metadata for better execution-environment handling

### ISSUE THREAD

**Issue by nwerker** [ansible-collections/microsoft.ad#45]
##### SUMMARY
Dear maintainers,

Please add and maintain the python requirements of the collection in its "Collection-level Metadata" so that people can more easily use the collection in execution-environments when using it with awx or ansible automation controller.

The Collection-level Metadata makes it more easy to include the collection in execution-environments, since the python dependencies will be automatically installed, when building the execution-environment with ansible-builder.

As you are already maintaining the requirements.txt file, this would simply require a few more lines of yaml in form of an execution-environment.yml file. I would be glad to contribute a pull request with the necessary lines of code later today. I'm also willing to contribute to testing and building example execution environments in the future, even if it involves an increase in dependencies.

Thanks in advance

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Metadata

##### ADDITIONAL INFORMATION
If you need further information about the Collection-level Metadata here is some documentation from the ansible-builder project [Documentation](https://ansible-builder.readthedocs.io/en/stable/collection_metadata.html).

**Comment by jborean93** [comment]
As per the conversation in https://github.com/ansible-collections/microsoft.ad/pull/46, the meta file is not needed because this collection already uses the default paths.
