### ISSUE TITLE
microsoft.ad.ldap inventory plugin filters on objectclass "computer" per default

### ISSUE THREAD

**Issue by tiagodcc** [ansible-collections/microsoft.ad#55]
##### SUMMARY
By default, the microsoft.ad.ldap inventory plugin uses the ldap filter `(objectClass=computer)`. Using the plugin parameter `filter`, it is possible to specify custom ldap filter definitions and search for specific objects in the ldap tree. However, the custom filter definition is always used in combination with the default filter.

This behavior leads to errors on systems that have a custom ldap/ad scheme and do not contain the objectClass `computer`.

It seems like the following code lines are responsible for the explained behavior:
https://github.com/ansible-collections/microsoft.ad/blob/6bf01b5f0ec466f709d3959fdc9e4b41d53c4551/plugins/inventory/ldap.py#L272-L282

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

microsoft.ad.ldap inventory plugin

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.0]
  config file = /home/USER/ansible.cfg
  configured module search path = ['/home/USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/USER/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.16 (main, May 29 2023, 00:00:00) [GCC 11.3.1 20221121] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection   Version
------------ -------
microsoft.ad 1.2.0
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(env: ANSIBLE_CACHE_PLUGIN) = jsonfile
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = awx_display
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
RETRY_FILES_ENABLED(env: ANSIBLE_RETRY_FILES_ENABLED) = False
```

##### OS / ENVIRONMENT

- LDAP server with a custom scheme, objectClass `computer` does not exist

##### STEPS TO REPRODUCE

To reproduce the issue, a ldap server with a custom scheme is required. Afterwards, an example of the inventory configuration is provided.
```yaml
---
plugin: microsoft.ad.ldap

### LDAP connection options

server: hostname.example.com
port: 389

encrypt: false
auth_protocol: simple
cert_validation: ignore

### Search Options

search_base: "ou=Test,DC=test,DC=com"
search_scope: subtree

filter: "(objectClass=test)"
```

When the configuration of the inventory is finished, the `ansible-inventory` command can be used to receive a list of all hosts.

```bash
ansible-inventory -i test.microsoft.ad.ldap.yml --list
```

##### EXPECTED RESULTS

The filters aren't combined.  The expected result is that the filter is set correctly and the query returns a list of all hosts in the ldap tree.

##### ACTUAL RESULTS

```paste below
[WARNING]:  * Failed to parse /home/USER/test.microsoft.ad.ldap.yml with ansible_collections.microsoft.ad.plugins.inventory.ldap plugin: 'attributeTypes'
```

**Comment by jborean93** [comment]
It is not possible as you've pointed out in the code where the `objectClass=computer` is always used even if a custom one was specified. The logic at the time was you will only ever want to retrieve back computer objects as targets to connect to as that is how AD seems to categories those types. We could technically add a new option to have it ignore this filter altogether if a new one was provided but I would be hesitant to do that by default.

I am curious if your LDAP server a Microsoft AD server or something else?

**Comment by tiagodcc** [comment]
My LDAP server isn't a Microsoft AD server. It uses a custom scheme that doesn't include the objectClass `computer`.
In Microsoft AD and other LDAP servers it is possible to change the default scheme and remove the objectClass `computer`. Therefore, I suggest to do this change with another option (e.g. a boolean `custom_filter`) to omit the default filter `objectClass=computer`. What do you think about this?

**Comment by jborean93** [comment]
The PR https://github.com/ansible-collections/microsoft.ad/pull/60 adds `filter_without_computer` as a new option that will avoid adding `objectClass=computer` to the final filter used.
