### ISSUE TITLE
microsoft.ad.group: Member names (sAMAccountName) with more than 20 characters not supported

### ISSUE THREAD

**Issue by mbx64** [ansible-collections/microsoft.ad#63]
##### SUMMARY

I use `microsoft.ad.group` to add members to an already existing group. This module complains it cannot find some groups that should be added as members. The groups it cannot find are groups that have a sAMAccountName with more than 20 characters.

I know there was an antique limit of 20 characters for sAMAccountNames. But since [Winodows Server 2000](https://learn.microsoft.com/en-us/windows/win32/adschema/a-samaccountname), we can have sAMAccountNames with max. length of 256.

The deprecated `community.windows.win_domain_group_membership` module actually *can* handle members whose names are longer than 20 characters.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

group

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.2]
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.9.16 (main, Jan 17 2023, 18:53:15) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/user/.local/lib/python3.9/site-packages/ansible_collections
Collection   Version
------------ -------
microsoft.ad 1.2.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/user/.ansible.cfg
DEFAULT_STDOUT_CALLBACK(/home/user/.ansible.cfg) = yaml
```

##### OS / ENVIRONMENT

Target OS: Windows Server 2019

##### STEPS TO REPRODUCE

```yaml
- name: Add group members
  microsoft.ad.group:
    name: Protected Users
    identity: S-1-5-21-XXX-525
    members:
      add:
        - GroupNameOK
        - GroupNameWayTooLongAndNotOK
```

##### EXPECTED RESULTS

OK

##### ACTUAL RESULTS

```paste below
fatal: [hostname]: FAILED! => changed=false 
  distinguished_name: CN=Protected Users,CN=Users,DC=my,DC=domain,DC=com
  msg: 'Failed to find the following ad objects for group members: ''GroupNameWayTooLongAndNotOK'''
  object_guid: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
```

**Comment by BenLangers** [comment]
Little to add except I have the exact same issue... 
Any workaround available to actually find those groups with the microsoft.ad.group module at the moment?

**Comment by jborean93** [comment]
Sorry for not replying to the issue earlier, it's certainly something we should be looking at to fix.

**Comment by jborean93** [comment]
This has been fixed with https://github.com/ansible-collections/microsoft.ad/pull/95.
